// SPDX-License-Identifier: GPL-3.0-or-later
//
// Reading a resolv.conf, and reading a dotted quad.
//
// Both exist because `getaddrinfo` is unusable here. It walks the nameserver
// list with a five-second timeout and two attempts each, so one unreachable
// server costs over ten seconds before the second is tried - and the TC002
// ships with `nameserver 114.114.114.114` first, which is unreachable from
// most of the world. Measured on the device: `http://example.com/` hit the
// fetcher's twenty-second backstop while `http://1.1.1.1/` answered 301
// immediately.
//
// So the adapter asks the nameservers itself with a two-second timeout. That
// needs the list, which needs this, which is pure text handling and belongs
// where it can be tested without a device.
#include "stipple/net/DnsMessage.h"

#include <cstdint>
#include <string>

#include "support/TestFramework.h"

namespace dns = stipple::net::dns;

namespace {

/// Readable in a test: 192.168.1.1 rather than 0xC0A80101.
constexpr std::uint32_t quad(std::uint32_t a, std::uint32_t b, std::uint32_t c,
                             std::uint32_t d) {
    return (a << 24) | (b << 16) | (c << 8) | d;
}

}  // namespace

STIPPLE_TEST(Ipv4, AnOrdinaryAddressParses) {
    std::uint32_t value = 0;
    STIPPLE_REQUIRE(dns::parseIpv4("192.168.1.1", value));
    STIPPLE_CHECK(value == quad(192, 168, 1, 1));

    STIPPLE_REQUIRE(dns::parseIpv4("0.0.0.0", value));
    STIPPLE_CHECK(value == 0u);

    STIPPLE_REQUIRE(dns::parseIpv4("255.255.255.255", value));
    STIPPLE_CHECK(value == 0xFFFFFFFFu);
}

STIPPLE_TEST(Ipv4, AnOctetOverTwoFiftyFiveIsRefused) {
    std::uint32_t value = 0;
    STIPPLE_CHECK(!dns::parseIpv4("192.168.1.256", value));
    STIPPLE_CHECK(!dns::parseIpv4("999.1.1.1", value));
}

STIPPLE_TEST(Ipv4, TooFewOrTooManyOctetsAreRefused) {
    // "192.168.1" is the case that matters: it is what somebody types when
    // they mean a network, and a parser that accepted it would silently
    // resolve to 192.168.0.1 or 0.192.168.1 depending on how it padded.
    std::uint32_t value = 0;
    STIPPLE_CHECK(!dns::parseIpv4("192.168.1", value));
    STIPPLE_CHECK(!dns::parseIpv4("192.168.1.1.1", value));
    STIPPLE_CHECK(!dns::parseIpv4("", value));
    STIPPLE_CHECK(!dns::parseIpv4(".", value));
    STIPPLE_CHECK(!dns::parseIpv4("1...1", value));
}

STIPPLE_TEST(Ipv4, TrailingRubbishIsRefusedRatherThanIgnored) {
    // Accepting the part before the rubbish would be inventing an address.
    std::uint32_t value = 0;
    STIPPLE_CHECK(!dns::parseIpv4("192.168.1.1x", value));
    STIPPLE_CHECK(!dns::parseIpv4("192.168.1.1 ", value));
    STIPPLE_CHECK(!dns::parseIpv4("192.168.1.1/24", value));
}

STIPPLE_TEST(Ipv4, AnOverlongOctetIsRefused) {
    // "0000" is four digits of a perfectly legal value, and some parsers
    // read a leading zero as octal. Neither is wanted.
    std::uint32_t value = 0;
    STIPPLE_CHECK(!dns::parseIpv4("0000.1.1.1", value));
    STIPPLE_CHECK(dns::parseIpv4("010.1.1.1", value));
    STIPPLE_CHECK(value == quad(10, 1, 1, 1));  // decimal, not octal
}

STIPPLE_TEST(Ipv4, AnIpv6AddressIsNotOne) {
    std::uint32_t value = 0;
    STIPPLE_CHECK(!dns::parseIpv4("::1", value));
    STIPPLE_CHECK(!dns::parseIpv4("2001:4860:4860::8888", value));
}

// --- resolv.conf -------------------------------------------------------------

STIPPLE_TEST(Resolver, TheDevicesOwnResolvConfIsRead) {
    // Byte for byte what a TC002 has. If this ever stops parsing, the device
    // stops resolving names and the only symptom is every fetch timing out.
    const std::string real =
        "nameserver 114.114.114.114\n"
        "nameserver 8.8.8.8\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(real, servers, dns::kMaxNameservers);

    STIPPLE_REQUIRE(count == 2);
    STIPPLE_CHECK(servers[0] == quad(114, 114, 114, 114));
    STIPPLE_CHECK(servers[1] == quad(8, 8, 8, 8));
}

STIPPLE_TEST(Resolver, CommentsAndBlankLinesAreSkipped) {
    const std::string text =
        "# Generated by something\n"
        "\n"
        "; another comment style\n"
        "search lan\n"
        "nameserver 192.168.1.1\n"
        "options edns0\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(text, servers, dns::kMaxNameservers);
    STIPPLE_REQUIRE(count == 1);
    STIPPLE_CHECK(servers[0] == quad(192, 168, 1, 1));
}

STIPPLE_TEST(Resolver, LeadingSpaceAndTabsAndCarriageReturnsSurvive) {
    // A file written on Windows, or edited by hand. Both happen.
    const std::string text =
        "\tnameserver\t10.0.0.1\r\n"
        "   nameserver 10.0.0.2   \r\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(text, servers, dns::kMaxNameservers);
    STIPPLE_REQUIRE(count == 2);
    STIPPLE_CHECK(servers[0] == quad(10, 0, 0, 1));
    STIPPLE_CHECK(servers[1] == quad(10, 0, 0, 2));
}

STIPPLE_TEST(Resolver, AnIpv6NameserverIsSkippedNotTreatedAsAnError) {
    // A machine with both listed is ordinary, and nothing below this speaks
    // IPv6 - so the v4 entry after it still has to be found.
    const std::string text =
        "nameserver 2001:4860:4860::8888\n"
        "nameserver 8.8.4.4\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(text, servers, dns::kMaxNameservers);
    STIPPLE_REQUIRE(count == 1);
    STIPPLE_CHECK(servers[0] == quad(8, 8, 4, 4));
}

STIPPLE_TEST(Resolver, TheKeywordHasToBeAWholeWord) {
    const std::string text =
        "nameserverfoo 1.2.3.4\n"
        "nameserver8.8.8.8\n"
        "nameserver 9.9.9.9\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(text, servers, dns::kMaxNameservers);
    STIPPLE_REQUIRE(count == 1);
    STIPPLE_CHECK(servers[0] == quad(9, 9, 9, 9));
}

STIPPLE_TEST(Resolver, DuplicatesAreDropped) {
    // resolv.conf files accumulate them, and a repeated dead server is the
    // same two-second timeout paid twice before anything works.
    const std::string text =
        "nameserver 8.8.8.8\n"
        "nameserver 8.8.8.8\n"
        "nameserver 1.1.1.1\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(text, servers, dns::kMaxNameservers);
    STIPPLE_REQUIRE(count == 2);
    STIPPLE_CHECK(servers[0] == quad(8, 8, 8, 8));
    STIPPLE_CHECK(servers[1] == quad(1, 1, 1, 1));
}

STIPPLE_TEST(Resolver, TheListIsBounded) {
    std::string text;
    for (int i = 1; i < 20; ++i) {
        text += "nameserver 10.0.0." + std::to_string(i) + "\n";
    }

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(text, servers, dns::kMaxNameservers);
    STIPPLE_CHECK(count == dns::kMaxNameservers);
}

STIPPLE_TEST(Resolver, AFileWithNoNameserverInItYieldsNone) {
    // Not an error here. The caller decides what to do with nothing, and it
    // has a better answer than this does.
    const std::string text = "search lan\ndomain lan\noptions ndots:1\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    STIPPLE_CHECK(dns::parseNameservers(text, servers, dns::kMaxNameservers) == 0);
    STIPPLE_CHECK(dns::parseNameservers("", servers, dns::kMaxNameservers) == 0);
}

STIPPLE_TEST(Resolver, AMalformedAddressIsSkippedNotHalfAccepted) {
    const std::string text =
        "nameserver 192.168.1\n"
        "nameserver 300.1.1.1\n"
        "nameserver \n"
        "nameserver 1.1.1.1\n";

    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count = dns::parseNameservers(text, servers, dns::kMaxNameservers);
    STIPPLE_REQUIRE(count == 1);
    STIPPLE_CHECK(servers[0] == quad(1, 1, 1, 1));
}

STIPPLE_TEST(Resolver, ALastLineWithNoNewlineStillCounts) {
    std::uint32_t servers[dns::kMaxNameservers] = {};
    const std::size_t count =
        dns::parseNameservers("nameserver 8.8.8.8", servers, dns::kMaxNameservers);
    STIPPLE_REQUIRE(count == 1);
    STIPPLE_CHECK(servers[0] == quad(8, 8, 8, 8));
}

STIPPLE_TEST(Resolver, NoOutputBufferIsHandled) {
    STIPPLE_CHECK(dns::parseNameservers("nameserver 8.8.8.8", nullptr, 4) == 0);
    std::uint32_t one = 0;
    STIPPLE_CHECK(dns::parseNameservers("nameserver 8.8.8.8", &one, 0) == 0);
}
