#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Turn golden-image fixtures into data the website can draw.

The site shows real panel output rather than mockups. These fixtures are the
frames the test suite compares against, so anything on the page is something
the renderer actually produced and CI still verifies - if a frame here looked
wrong, a test would be failing.

    python3 tooling/site/build-frames.py

Writes site/frames.js: the frames, and the device's 5x7 font.

The font is parsed out of firmware/src/text/Font5x7.cpp rather than redrawn,
so the clock on the website is set in exactly the glyphs the hardware uses.
There is one font on this device and there will only ever be one - a 2x scale
would be fourteen rows tall and leave no room for anything else - which is
what makes exporting it worth doing at all.

Each fixture is 52 x 16 x 3 bytes. Encoded as one base64 string per frame,
which is about 3.3 KB each - small enough that the whole set costs less than a
single screenshot would.
"""

import base64
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "firmware" / "tests" / "testdata"
FONT_SRC = ROOT / "firmware" / "src" / "text" / "Font5x7.cpp"
OUT = ROOT / "site" / "frames.js"

WIDTH, HEIGHT = 52, 16
EXPECTED = WIDTH * HEIGHT * 3

# Only the frames the page actually uses, with the caption each carries.
# Naming them explicitly rather than globbing keeps a new test fixture from
# silently appearing on the website.
WANTED = [
    ("splash-page-one", "The boot splash, over a travelling wave"),
    ("splash-page-two", "Then the address, so you know where to find it"),
    ("clock-minimal", "The clock"),
    ("clock-secondsbar", "A seconds bar, if you prefer"),
    ("clock-calendar", "Date and weekday"),
    ("stopwatch-running", "The stopwatch, counting"),
    ("stopwatch-stopped", "Stopped, in a colour you can read across a room"),
    ("scene-dashboard", "A custom app: a progress bar and a graph"),
    ("scene-living-room", "Another: an icon, a temperature, scrolling text"),
    ("icon-thermometer", "Icons are raw frames, converted in the browser"),
    ("text-alphabet", "The whole 5x7 font"),
    ("test-pattern-frame-025", "The test pattern, for checking a panel"),
]


def read_font() -> dict:
    """Codepoint -> [advance, seven row bitmaps], straight from the firmware."""
    text = FONT_SRC.read_text(encoding="utf-8")
    entries = re.findall(
        r"\{0x([0-9A-Fa-f]{4})u,\s*(\d+),\s*\{([^}]*)\}\}", text
    )
    glyphs = {}
    for code, advance, rows in entries:
        values = [r.strip() for r in rows.split(",")]
        if len(values) != 7:
            continue
        bits = []
        for value in values:
            # The source writes them as 0b00000 binary literals.
            bits.append(int(value.replace("0b", ""), 2))
        glyphs[str(int(code, 16))] = [int(advance)] + bits
    return glyphs


def main() -> int:
    frames = []
    for name, caption in WANTED:
        path = FIXTURES / (name + ".rgb")
        if not path.exists():
            print("build-frames: missing fixture %s" % path, file=sys.stderr)
            return 1
        data = path.read_bytes()
        if len(data) != EXPECTED:
            print(
                "build-frames: %s is %d bytes, expected %d - has the panel size changed?"
                % (name, len(data), EXPECTED),
                file=sys.stderr,
            )
            return 1
        frames.append(
            {
                "id": name,
                "caption": caption,
                "rgb": base64.b64encode(data).decode("ascii"),
            }
        )

    font = read_font()
    if len(font) < 90:
        print(
            "build-frames: only parsed %d glyphs, which means the font table "
            "changed shape rather than shrank" % len(font),
            file=sys.stderr,
        )
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(frames, indent=0, separators=(",", ":"))
    OUT.write_text(
        "// Generated by tooling/site/build-frames.py - do not edit.\n"
        "//\n"
        "// Real output from the renderer, taken from the golden-image fixtures\n"
        "// the test suite compares against. Nothing here is a mockup.\n"
        "export const PANEL = { width: %d, height: %d };\n"
        "export const FRAMES = %s;\n"
        "// The device's 5x7 font, parsed from firmware/src/text/Font5x7.cpp.\n"
        "// codepoint -> [advance, row0..row6]; each row is five bits, MSB left.\n"
        "export const FONT = %s;\n"
        % (WIDTH, HEIGHT, body, json.dumps(font, separators=(",", ":"))),
        encoding="utf-8",
    )

    total = sum(len(f["rgb"]) for f in frames)
    print(
        "build-frames: %d frames, %d glyphs, %.1f KB"
        % (len(frames), len(font), OUT.stat().st_size / 1024)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
