// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <cstdint>

namespace notrix {
namespace audio {

/// Generates PCM for a tone, a frame at a time.
///
/// Core rather than platform, and pure: what a beep sounds like is not a fact
/// about SigmaStar hardware, and the arithmetic that decides it is exactly the
/// kind of thing that should be testable without a speaker in the room.
///
/// Pulled a frame at a time rather than rendered into a buffer up front,
/// because blueprint §16 says audio must never block rendering: the device
/// hands the driver one short frame per tick and returns, instead of sitting in
/// a loop for the length of the sound.
class ToneGenerator {
public:
    /// Sample rate the caller will play at. The TC002 runs its speaker at
    /// 16 kHz - read off the vendor application's own configuration rather
    /// than chosen - but nothing here depends on that number.
    explicit ToneGenerator(int sampleRate = 16000) noexcept : sampleRate_(sampleRate) {}

    /// Start a tone. Replaces whatever was playing: a device that queued beeps
    /// would fall behind the thing it is beeping about.
    void start(int frequencyHz, int durationMillis) noexcept;

    /// Stop immediately.
    void stop() noexcept { remaining_ = 0; }

    bool playing() const noexcept { return remaining_ > 0; }

    /// Samples still to produce.
    int remaining() const noexcept { return remaining_; }

    /// 0-100. Applied here rather than through the hardware's own volume
    /// control, which on this device refuses every value it was offered.
    void setVolumePercent(int percent) noexcept;
    int volumePercent() const noexcept { return volumePercent_; }

    /// Fill up to `count` samples. Returns how many were written; a short
    /// return means the tone ended inside this frame.
    int fill(std::int16_t* samples, int count) noexcept;

private:
    int sampleRate_;
    int remaining_ = 0;

    /// Samples in half a cycle. A square wave is generated by counting to this
    /// and flipping, which needs no table and no division per sample.
    int halfPeriod_ = 0;
    int phase_ = 0;
    bool high_ = true;

    int volumePercent_ = 60;

    /// Peak sample value at full volume.
    ///
    /// Deliberately short of full scale. This drives a small speaker in a
    /// clock, and a square wave at full amplitude is both unpleasant and the
    /// sort of thing that makes people turn a device off rather than down.
    static constexpr int kAmplitude = 9000;
};

}  // namespace audio
}  // namespace notrix
